timezone: Europe/London

title: "Minecraft: Pocket Edition"

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
 
defaults:
  - scope:
      path: ""
      type: pages
  - scope:
      path: ""
      type: wiki
    values:
      layout: page
      secondarytitle: MCPE Wiki
  - scope:
      path: ""
      type: tutorials
    values:
      layout: page
      secondarytitle: MCPE Tutorials
